chipsalliance/fpga-tool-perf

fpgaperf.py, icecubed.sh, project/murax.json
Bunch of small fixes while trying to test all the PnR tools with the `murax` project on the `up5k` part.
=> Small fixes while testing Murax on up5k

README.md, fpgaperf.py, project/oneblink-arty.xdc
This PR adds initial support for Vivado. It uses edalize for handling the tool. Edalize from  https://github.com/olofk/edalize/pull/54 should be used with this code.
Most of the resources usage are read from utilization report, currently the reported ones are limited to the set reported so far for different tools. This should be probably expanded.
Also, max_frequency is not yet extracted.
=> Add initial Vivado support

README.md, fpgaperf.py, project/oneblink-zybo-z7.xdc, vivado.py
This PR extracts Vivado flow from the main script. Also Yosys -> Vivado flow has been added.
This code requires edalize from this PR: https://github.com/olofk/edalize/pull/103
=> Update Vivado flow

exhaust.py, fpgaperf.py, src/oneblink/constr/vivado-yosys/xc7_a35t_cpg236-1_basys3.xdc, src/oneblink/constr/vivado-yosys/xc7_a35t_csg324-1_arty.xdc, src/oneblink/constr/vivado-yosys/xc7_z010_clg400-1_zybo.xdc, vivado.py
This PR fixes the vivado-yosys reports generation.
=> Fix vivado yosys reports

.gitmodules, Makefile, conf/environment.yml, conf/requirements.txt, exhaust.py, fpgaperf.py, icestorm.py, project/blinky.json, src/blinky/blinky.v, src/blinky/constr/nextpnr/xc7_a35t_csg324-1_arty.xdc, src/blinky/constr/vpr/xc7_a35t_csg324-1_arty.pcf, symbiflow.py, vivado.py
This PR adds nextpnr to the flow, as well as a new blinky test that works on the RGB leds of the arty platform.
The blinky test is targetted, for now for:
- VPR;
- Nextpnr.
This PR depends on https://github.com/SymbiFlow/edalize/pull/28
Follow up PRs will include:
- QoR extraction for nextpnr
- Integration of some of the pre-existing tests to address nextpnr
=> Add nextpnr

Makefile, conf/environment.yml, conf/requirements.txt, env.sh
This PR changes the symbiflow package that has new files location, as well as a far more reduced size.
=> Use new symbiflow

src/picosoc/constr/vivado/xc7_a35t_cpg236-1_basys3.xdc
=> picosoc: fix xdc

.gitmodules, project/hamsternz-hdmi.json, src/hamsternz-hdmi/constr/vivado/xc7_a200t_fbg484-1_nexys.xdc, vivado.py
=> Add hamsternz hdmi

fpgaperf.py, symbiflow.py, utils.py, vivado.py
This PR moves have_exec to utils, and fixes the have_exec call in symbiflow.
=> symbiflow: fix check-env

symbiflow.py
The latest revision of Yosys didn't work with fpga-tool-perf without this.
=> Use a regex for to match time from Yosys

icestorm.py, project/blinky.json, project/picosoc.json, src/blinky/constr/arty.xdc
=> projects: added some missing toolchains

fasm2bels.py, symbiflow.py
=> vpr: fix run time extraction to have data taken from the log files

fasm2bels.py
=> fasm2bels: add capnp schema dir

README.md
This pull request:
- Adds instructions for inserting a new project
- Makes many minor changes for consistency and clarity, including reordering some sections
=> Adding New Project Instructions to README

Makefile, exhaust.py, fpgaperf.py, runner.py, symbiflow.py
This PR requires an install package from: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1504
=> symbiflow: add seed option

conf/environment.yml
=> db: pin the prjxray-db conda package

symbiflow.py, toolchain.py
=> Add overhead to VPR run-times

project/ibex.json, project/murax.json, project/picorv32.json, project/picosoc-simpleuart.json, project/picosoc-spimemio.json, project/picosoc.json, project/vexriscv.json
=> fasm2bels: add the remaining vpr-fasm2bels tests

symbiflow.py, toolchain.py, vivado.py
This PR assumes that `MiB` from vpr and `MB` from vivado are not the same unit.
Fixes #216 
=> Add wirelength and max_rss to meta.json

Makefile, conf/environment.yml, conf/requirements.txt, project/bram_n1.json, project/bram_n2.json, project/bram_n3.json, project/dram_test_64x1d.json
=> tools: update to latest version

runner.py
=> runner: fix error message output when failing a task

README.md
=> Change make conda to make env

symbiflow.py
Fixes https://github.com/SymbiFlow/fpga-tool-perf/issues/242
=> symbiflow: fix extraction of runtimes

src/blinky/constr/arty.sdc, src/blinky/constr/basys3.sdc, symbiflow.py
=> symbiflow: fix vpr frequencies

.github/kokoro/steps/hostsetup.sh, Makefile, README.md, conf/common/requirements.txt, conf/nextpnr/environment.yml, conf/nextpnr/requirements.txt, conf/quicklogic/environment.yml, conf/quicklogic/requirements.txt, conf/symbiflow/requirements.txt, env.sh, fasm2bels.py, icestorm.py, symbiflow.py
Fixes #245 
This PR adds separate environment for nextpnr toolchain.
=> Add separate env for nextpnr toolchain

project/iir.json, src/murax/constr/nexys-video.sdc, src/picosoc-simpleuart/constr/nexys-video.xdc, src/picosoc-spimemio/constr/nexys-video.xdc, src/vexriscv/constr/nexys-video.xdc, toolchain.py
=> nexys: add missing clock constraints

.github/kokoro/nightly.cfg
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>
=> Adding configuration for nightly run.

toolchains/symbiflow.py
=> nextpnr: fixed clock data

.github/kokoro/nightly.sh, Makefile, conf/symbiflow/requirements.txt, project/baselitex.json, project/daisho-usb3.json
=> symbiflow: update version

Makefile
This updates the symbiflow arch defs package to the latest version.
Currently, the VTR version is the latest one tested in the arch-defs master
=> symbiflow: update architecture packages

conf/nextpnr/requirements.txt, conf/symbiflow/requirements.txt
=> requirements: fix requirements after pip upgrade

conf/nextpnr/requirements.txt, conf/symbiflow/requirements.txt
=> env: fix conda python requirements

README.md
This PR fixes Arty Board name in the main README file
=> Fix Arty Board name in the main README

.github/kokoro/continuous.cfg, .github/kokoro/nightly.cfg, .github/kokoro/nightly.sh, .github/kokoro/presubmit.cfg, .github/kokoro/test.sh, Makefile, exhaust.py, infrastructure/runner.py, project/picosoc-spimemio.json
=> exhaust: allow selecting how many cpus to use

src/zynq-ps7-counter/constr/zybo.xdc
=> zynq-counter: fix period

conf/nextpnr/environment.yml, conf/nextpnr/requirements.txt, conf/symbiflow/environment.yml, conf/symbiflow/requirements.txt
The packages have been also updated to their latest versions.
=> nextpnr: Use Conda packages from LiteX-Hub channel

conf/nextpnr/requirements.txt, conf/symbiflow/requirements.txt, test/test_all.py
=> format: reformat code using newest yapf

conf/symbiflow/requirements.txt
=> conf: symbiflow: remove pinned versions from requirements

conf/symbiflow/environment.yml, exhaust.py, fpgaperf.py, other/vendors.json, toolchains/toolchain.py, toolchains/vivado.py
This PR adds new toolchain using vivado + yosys with uhdm frontend.
=> Add VivadoYosysUhdm toolchain

conf/common/requirements.txt, conf/symbiflow/environment.yml, toolchains/icestorm.py, toolchains/symbiflow.py, toolchains/vivado.py
Update yosys-uhdm to newer version
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>
=> Update to new edalize

.github/kokoro/continuous.cfg, .github/kokoro/nightly.cfg, .github/kokoro/presubmit.cfg, infrastructure/runner.py
This PR does the following:
- fixes the regex for kokoro to upload the results files
- removes uninteresting data from the results and uses gzip to compress the data
=> Adjust results file

conf/nextpnr/environment.yml, fpgaperf.py, other/boards.json, other/vendors.json, project/oneblink.json, project/picorv32.json, project/picosoc-simpleuart.json, project/picosoc-spimemio.json, project/up5k-nes.json, src/oneblink/constr/lifcl-40.pdc, toolchains/oxide.py, toolchains/symbiflow.py, toolchains/toolchain.py
This PR partially addresses issue #333 by adding oxide toolchain support.
Current edalize changes are on a topic branch.
It's still WIP as it still needs some scripts that would extract the run time infomation as they are currently presented as N/A
=> Add oxide toolchain support

.github/workflows/ci.yml, .github/workflows/gh-pages.yml, results/.gitignore, results/Makefile, results/README.md, results/color.py, results/fetch_meta.py, results/fix_clock_info.py, results/gen.py, results/generate_graph_page.py, results/generate_index_page.py, results/html/graphviz.html, results/html/index.html, results/html/table.html, results/jinja2_templates.py, results/project_results.py, results/requirements.txt, results/testentry.py
This PR adds scripts to fetch and build an HTML representation of the results generated by FPGA tool perf CI.
It also adds a cron scheduled workflow to automatically build and deploy on GH pages.
=> results: add GH pages generation and deployment

conf/quicklogic/requirements.txt
=> quicklogic: pin qlf-fasm

.github/kokoro/steps/hostsetup.sh, .gitmodules, Makefile, conf/nextpnr/environment.yml, env.sh, infrastructure/tasks.py, project/axi-lite-reg.json, project/daisho-usb3.json, project/hamsternz-hdmi.json, project/picosoc.json, project/vexriscv.json, toolchains/symbiflow.py, toolchains/toolchain.py
=> bump interchange

Makefile, __init__.py, conf/common/requirements.txt, infrastructure/__init__.py, infrastructure/tasks.py, results/Makefile, results/__init__.py, results/fetch_meta.py, results/generate_html.py, results/generate_index_page.py, results/html/index.html, results/html/table.html, results/project_results.py, results/requirements.txt, results/testentry.py, setup.py, toolchains/__init__.py, utils/__init__.py
This PR changes the initial view of the results.
The first page will have a list of available boards, and for each, all the designs enabled for them and the currently passing/skipped/failed toolchains.
=> Refactor results page

infrastructure/tasks.py
Fixes https://github.com/SymbiFlow/fpga-tool-perf/issues/369
=> tasks: use correct project name

infrastructure/tasks.py, other/boards.yaml, results/generate_index_page.py, toolchains/toolchain.py
=> tasks: fix inconsistency in project name and project JSON file reference

results/html/index.html
=> bump RapidWright

Makefile
Added listing actual version of installed conda packages to the Makefile so that they are present in CI logs.
=> List conda package versions

.github/workflows/tests.yml
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
=> CI: run tests every 4h

other/boards.yaml, results/result_entry.py, toolchains/radiant.py
This PR fixes the failing [`generate_page_results`](https://github.com/chipsalliance/fpga-tool-perf/runs/4970815857?check_suite_focus=true) CI
=> Fix ice40 board definition

results/result_entry.py
=> results: sanitize legacy nexus device names

.github/workflows/tests.yml
=> Use nonpreemtible machines

Makefile, conf/common/requirements.txt, conf/nextpnr/requirements.txt, conf/symbiflow/requirements.txt, env.sh, project/baselitex-nexys-video.yaml, project/picosoc.yaml, toolchains/symbiflow.py
=> env: use latest packages and start transition to f4pga

.github/workflows/scripts/install.sh, Makefile, conf/common/requirements.txt, exhaust.py, toolchains/symbiflow.py
Blocked by https://github.com/SymbiFlow/edalize/pull/119.
Based on #455.
=> toolchains/symbiflow: 'vpr_options' is a list

.github/workflows/Pages.yml, .github/workflows/Suite.yml
=> ci: fix reference to default branch

toolchains/nextpnr.py
Signed-off-by: Maciej Kurc <mkurc@antmicro.com>
=> Hotfix for nextpnr-fpga-interchange-already-synth

.github/workflows/Tests.yml
This fixes the latest formatting tests in CI in the [automerge flow](https://github.com/chipsalliance/fpga-tool-perf/actions/runs/3457564756/jobs/5771114751)
=> ci: Do not check formatting in untracked files

.github/scripts/install.sh
Install the libtbb-dev package to resolve problems with running nextpnr toolchains.
=> ci: Install the libtbb package
