fpgaperf.py
src/baselitex/arty.sdc
src/baselitex/baselitex_arty.v
src/baselitex/baselitex_arty_vivado.xdc
symbiflow.py
toolchain.py
vivado.py

This PR adds timing results extraction for Vivado and Symbiflow toolchains.
Bellow, are example results for litex-linux test:
Vivado:
command:
```
python3 fpgaperf.py --toolchain vivado --project litex-linux --family "xc7" --device "a35ti" --package "csg324-1L" --pcf src/baselitex/baselitex_arty_vivado.xdc
```
results:
```
Family: xc7
Device: a35ti
Package: csg324-1L
Project: litex-linux
Toolchain: vivado
Strategy: None
Carry: False
Seed: default
Timing:
nop:             0.007
bitstream:       178.580
Max frequency in clock domain soc_pll_clk200 849.618 MHz
Max frequency in clock domain eth_rx_clk 122.175 MHz
Max frequency in clock domain eth_tx_clk 107.021 MHz
Max frequency in clock domain sys_clk 87.835 MHz
Resource utilization
BRAM:                81.0
CARRY:               260
DFF: …
```

Timing info

---

.gitattributes

```
76.28%  Coq
18.57%  Verilog
3.58%   Python
1.57%   Shell
0.01%   Makefile
Makefile:
Makefile
Shell:
csv.sh
exhaust.sh
icecubed.sh
jenkins.sh
pcf_test.sh
radiant.sh
vpr_xml.sh
wrappers.sh
Python:
fpgaperf.py
icestorm.py
sow.py
symbiflow.py
test/test_all.py
toolchain.py
utils.py
vivado.py
wrapper.py
Coq:
src/baselitex/VexRiscv_Linux.v
src/baselitex/baselitex_arty.v
src/murax/Murax.v
src/picorv32_def.v
Verilog:
src/ibex/clkgen_xil7series.v
src/ibex/ibex_alu.v
src/ibex/ibex_compressed_decoder.v
src/ibex/ibex_controller.v
src/ibex/ibex_core.v
src/ibex/ibex_core_tracing.v
src/ibex/ibex_cs_registers.v
...
```
```
69.46%  Python
30.44%  Shell
0.10%   Makefile
Makefile:
Makefile
Shell:
csv.sh
exhaust.sh
icecubed.sh
jenkins.sh
pcf_test.sh
radiant.sh
vpr_xml.sh
wrappers.sh
Python:
fpgaperf.py …
```

Adding .gitattributes to import GitHub language stats.

---

src/ibex/constr/vivado-yosys/xc7_a35t_csg324-1_arty.xdc

It looks like vivado-yosys flow for ibex was accidentally removed during refactoring.
This PR restores it.

ibex: enable vivado-yosys toolchain

---

toolchain.py

Use string `join()` method to concatenate string with `_` separator. This eliminates the need for py3-only `nonlocal` keyword.

Simplify optstr() method.

---

exhaust.py

This PR adds the possibility to output the error when running exhaust. This helps debug issues that appear in CI and not on the local machine.

Fix output when error

---

exhaust.py

This PR enables the user to select family/device/package/board when running exhaust.

exhaust: better build dir extraction and added user selection options

---

dataframe.py
exhaust.py
fpgaperf.py
symbiflow.py
toolchain.py
vivado.py

This PR makes results more uniform and creates a true DataFrame that can be queried to extract information on the runs.

Uniform results data

---

Makefile
conf/environment.yml
dataframe.py
exhaust.py
fpgaperf.py
runner.py
symbiflow.py
tasks.py
tool_parameters.py
tool_parameters/vpr/parameters.json
toolchain.py

This PR has a double purpose:
- allowing to inject custom parameters for the tool (currently it is enabled for VPR only, but could be expanded in the future to be more flexible).
- make it possible to easily running multiple times the tests to gather more samples.
Note: Given that the exhaust script is used mainly to perform a batch of tests, I have limited the freedom degree to be able to choose only `toolchains` and `projects` (from a user perspective).
The user can still run single tests using `fpgaperf.py`.
TODO:

Custom parameter injection and multiple tests run

---

symbiflow.py

The corresponding PR for edalize: https://github.com/SymbiFlow/edalize/pull/47

Add yosys_synth_options and use the options from nextpnr-xilinx

---

fasm2bels.py
fpgaperf.py
project/blinky.json
src/blinky/blinky.v
src/blinky/constr/arty.pcf
src/blinky/constr/arty.xdc
symbiflow.py
tasks.py

This enables to run fasm2bels on the nextpnr-generated bitstreams.
As a side effect, this PR moves fasm2bels related flows in a separate file to keep things cleaner.
This fixes https://github.com/SymbiFlow/fpga-tool-perf/issues/159

nextpnr: enable fasm2bels

---

Makefile
conf/environment.yml
project/baselitex.json
project/blinky.json
project/murax.json
project/picosoc.json
src/ibex/constr/arty.sdc
vivado.py

This PR modifies the yosys version to the latest master+wip, so we can enable nextpnr-xilinx as well for all the supported tests.
In addition this PR modifies the following:
- fix to ibex SDC to have clock correctly constrained;
- do not use abc9 in yosys+vivado flow: this needs to be fixed. Apparently the ibex test results in abc9 issues, which end up in segfaults.

use latest yosys

---

exhaust.py
fpgaperf.py
runner.py

New PR with identical changes as in [PR #176](https://github.com/SymbiFlow/fpga-tool-perf/pull/176).
Added a logger for both fpgaperf.py and exhaust.py, that is turned on if --verbose is specified. Also added messages that will be printed through the logger under the DEBUG level.
Also changed the directory to which exhaust runs are saved from `build` to `build/_exhuaust-runs`.

Using Logger to implement --verbose functionality

---

icestorm.py

This PR is to have frequency results in the meta.json file for ice40 consistent with all the other results from other toolchains. Fixes https://github.com/SymbiFlow/fpga-tool-perf/issues/190

icestorm: have max_freq expressed in Hz instead of MHz

---

conf/environment.yml
conf/requirements.txt

This is to have green CI until https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1626 is merged and we can have an updated install package with the correct fasm features

tools: pin nextpnr-xilinx and fasm2bels

---

symbiflow.py
toolchain.py
utils.py

Update overhead calculation for vpr to `total step run` - `useful step work`.
This PR also adds possibility to calculate time with `Timed` class without automatic adding it to printable `runtimes` collection.

vpr: update overhead calculation

---

fpgaperf.py
runner.py
toolchain.py

This pull request implements `fpgaperf.py`'s `--overwrite` functionality by deleting the previous build of the same location. For example:
```
python3 fpgaperf.py --toolchain vivado --board basys3 --project oneblink
```
Running the above command will result in the folder: `fpga-tool-perf/build/oneblink_vivado_xc7_a35tcpg236-1_basys3_xdc_carry-n`. Repeating the same command has varying results, often either failing or resulting in inaccurate runtimes.
```
python3 fpgaperf.py --toolchain vivado --board basys3 --project oneblink --overwrite
```
Running the same command with `--overwrite` deletes the previous `fpga-tool-perf/build/oneblink_vivado_xc7_a35tcpg236-1_basys3_xdc_carry-n` folder and its contents and creates the folder again, where it then runs the build with no interference from …

Implemented --overwrite Functionality

---

exhaust.py
fpgaperf.py
icecube.py
project/baselitex.json
project/picorv32.json
project/picosoc-simpleuart.json
project/picosoc-spimemio.json
project/picosoc.json
project/vexriscv.json
radiant.py
vivado.py

There was an issue with `exhaust.py` runs, which would print the stats of all of the saved builds, even if only a certain project or toolchain was specifically being tested like in running `python3 exhaust.py --toolchain vivado-yosys`.
This pull request fixes this by adding conditions to only print the runs that match the specified toolchain and project arguments, just as the condition to only print runs of the specified build name and number already exists.
I also fixed the names of the `vivado-yosys` toolchain and many of the projects to match the names that the user inputs to run them. Odd to run the `vivado-yosys` toolchain and then have it called the `yosys-vivado` toolchain in the build summary. Naming the synthesis tool after the primary tool seems to match the rest of the …

Exhaust Printing Fix

---

project/bram_n1.json
project/bram_n2.json
project/bram_n3.json
project/dram_test_64x1d.json

Add missing vendor key to bram 1, 2, 3 and dram projects. This key is required for `--list-combinations`.

Add vendors key to bram 1, 2, 3 and dram projects

---

project/bram_n1.json
src/bram/scalable_proc.v

This PR fixes problem with shift register when NUM_PROCESSING_UNITS==1 and enables bram_n1 vivado test.
Fixes #193 

Enable bram_n1 vivado test

---

exhaust.py
runner.py

Added an argument that overwrites previous builds to re-run any builds that previously existed. Where it would previously give False for 'overwrite' when calling the fpgaperf run function, now it provides self.overwrite, which is true if --overwrite is specified in the command and false otherwise.

Exhaust `--overwrite` argument

---

exhaust.py

1. Gives the `--project` and `--toolchain` arguments choices like their counterparts in `fpagperf.py`. This way, `exhuast.py` can recognize bad arguments and print out the user's options.
2. Creates and adds functionality to the `--board` argument. This means you can now specify a board or boards you want to be tested by the `exhuast.py` run.

Exhaust: Argument Fix and --board

---

symbiflow.py

For symbiflow targets, RAMB36 were not taken into account in the resource usage extraction.
Moreover, each RAMB36 will count as double, as underneath, it uses two RAMB18

symbiflow: fix bram calculation

---

runner.py
toolchain.py

1. Adds the `Writing to <out_prefix>` statement to the exhaust run. Serves the same purpose as it does in `fpgaperf.py`.
2. Changes `os.mkdir()` to `os.makedirs()`. We recently made this change to the `exhaust.py` run. It will simply allow for more specific directory paths if the user is so inclined, without failing if there are multiple folders in the path yet to be created. This also makes it easier to use the `--out-prefix` and `--out-dir` arguments separately.

Minor Enhancements for Usability

---

Makefile
exhaust.py

This PR set error code, only when required test failed. This allows to run all tests without ``--only-required`` flag and error code (and CI status) will be ``1`` only when test that are marked as required will fail.
This will reduce CI build time, by not building the same test 2 times.

exhaust: set error code only when required test failed

---

exhaust.py

Most changes originally made by this PR are either implemented by or made irrelevant by recent commits. However, I still think it would be nice for the "Total Runs:" statement to be there just for further clarity, especially in cases where there aren't any actual runs, but a table is still printed.
```
$ python3 exhaust.py --toolchain nextpnr-ice40 --project oneblink
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.51s/test]
+-------------+---------------+---------+----------+------------+------------+----------+-------------+--------+
| Project     | Toolchain     | Family  | Part     | Board      | Build Type | Build N. | Options     |        |
+-------------+---------------+---------+----------+------------+----- …
```

Exhaust Results Improvements

---

fasm2bels.py
icecube.py
radiant.py
symbiflow.py
toolchain.py
vivado.py

I found two issues with timing consistency that I have addressed with this pull request.
Each toolchain's runtime includes a `prepare` time, as well as a `self.add_runtimes()`. The problem is that while `prepare` time is included in symbiflow's `total` time, it is not included in vivado's total time. The other inconsistency is that the `self.add_runtimes()` function is included in symbiflow's `total` but not in vivado's.
These are my solutions:
1. In `symbiflow.py`, I removed the `self.add_runtimes()` from the `total` runtime, since it isn't actually a part of the running toolchain, simply a gathering of runtimes. This simply meant deleting a tab from it, so it takes place after (and not during) the `with Timed(self, 'total'):` code block.
2. In `vivado.py`, I moved the `with Timed(self, …

Timing Consistency Between Toolchains

---

symbiflow.py

Yosys version's output is too long, as it contains all the compilation flags as well. This PR extracts the commit hash to be saved in the meta.json files.

yosys: get reduced version string

---

.github/kokoro/steps/hostsetup.sh
Makefile
env.sh

This PR allows to use a different environment file for conda. Once we have archdefs producing "latest" artifacts links, we can start having automated updates on the symbiflow packages, based on the symbiflow-arch-defs updates.
It also reworks the way symbiflow and quicklogic data files are downloaded and installed.

conda: allow using an external environment file

---

conf/nextpnr/environment.yml

nextpnr-env: use same yosys and yosys-plugins as symbiflow-env

---

toolchains/fasm2bels.py
toolchains/icecube.py
toolchains/icestorm.py
toolchains/radiant.py
toolchains/toolchain.py

Something got moved preventing --check-env working for certain toolchains. This was easily fixed by importing have_exec to those toolchain's python files.

Fixed --check-env Functionality

---

fpgaperf.py
other/vendors.json

With recent changes, the `--list-combinations` functionality broke. I got it up and running again. It now uses the `"vendor"` and `"required_toolchains"` sections of each project's json file to determine whether a project/toolchain/board combination is "Supported" or "Missing".

Fixed --list-combinations Functionality

---

project/zynq-ps7-counter.json
src/zynq-ps7-counter/constr/zybo.xdc
src/zynq-ps7-counter/counter_zynq.v

tests: add a zynq counter test that uses the PS7

---

project/axi-lite-reg.json
src/axi-lite-reg/AxiPeriph.v
src/axi-lite-reg/axi_reg.v
src/axi-lite-reg/constr/zybo.xdc

This test's purpose is to check the PS7 correctness, and is meant to be used in the [xc7-automatic-tester](https://github.com/SymbiFlow/symbiflow-xc7z-automatic-tester).

tests: add axi-lite-reg test for zynq that uses PS7

---

conf/quicklogic/environment.yml

`quicklogic-vtr` had to stay at the same version because testing on
`symbiflow-examples` showed that newer versions are incompatible with
the currently used quicklogic toolchain.
Other packages are in the versions built from their latest source
commits.

quicklogic: Use Conda packages from LiteX-Hub channel

---

conf/quicklogic/environment.yml

Related to: https://github.com/SymbiFlow/fpga-tool-perf/pull/317
This PR pins tbb version to fix issue with missing ``libtbb.so.2``.

quicklogic: pin tbb version

---

.github/kokoro/steps/hostsetup.sh
Makefile
conf/symbiflow/environment.yml

This PR tries to unify created environment between CI and user.
Up to now, kokoro CI was explicitly selecting environment file that is downloaded as part of symbiflow-arch-def (and it was not using ``conf/symbiflow/environment.yml`` at all), but when user follows README there is no information about selecting ``ENVIRONMENT_FILE`` explicitly when creating symbiflow environment, so for user, ``conf/symbiflow/environment.yml`` is used.
This PR changes target ``install_symbiflow`` to first install environment from ``conf/symbiflow/environment.yml`` and then updates it with ``env/symbiflow/environment.yml`` file. This way, we are installing dependencies from both files.

make env: update base env with symbiflow environment

---

conf/nextpnr/requirements.txt
conf/symbiflow/requirements.txt

Remove directly rapidyaml reference from requirements.

---

.github/kokoro/continuous.cfg
.github/kokoro/nightly.cfg
.github/kokoro/presubmit.cfg
exhaust.py
infrastructure/runner.py
project/baselitex-nexys-video.json
project/baselitex.json
project/blinky.json
project/bram-n1.json
project/bram-n2.json
project/bram-n3.json
project/dram-test-64x1d.json
project/ibex.json
project/murax.json
project/picosoc-simpleuart.json
project/picosoc.json
project/vexriscv.json
project/zynq-ps7-counter.json
toolchains/fasm2bels.py
toolchains/icestorm.py
toolchains/toolchain.py
utils/sow.py

This PR does the following:
- allows to create a final results file containing all the various `meta.json` files from all builds
- given that different toolchain use different clock naming conventions, a `clock_alias` field can now be used in the project description to unify and correctly group the frequency results under the same clock name for different toolchains.

Merge results in single file

---

conf/symbiflow/environment.yml
toolchains/vivado.py

This PR updates yosys-uhdm conda package to use ``uhdm`` frontend as a plugin to ``yosys``.

Update yosys-uhdm to use uhdm frontend as a plugin

---

conf/nextpnr/environment.yml
exhaust.py
fpgaperf.py
infrastructure/runner.py
other/boards.json
project/axi-lite-reg.json
project/dram-test-64x1d.json
results/fetch_meta.py
results/generate_html.py
results/generate_index_page.py
results/project_results.py
results/testentry.py
toolchains/toolchain.py

This PR does the following:
- lets the toolchains output a failed/succeeded status field in the meta.json. If a task fails, the error message gets attached to the meta.json.
- the initial view of the results gh page displays the set of all available boards, and for each, all the designs enabled for them and the currently passing toolchains.

results: add also failed meta results

---

results/generate_index_page.py
results/result_entry.py
toolchains/nextpnr.py
toolchains/symbiflow.py
toolchains/toolchain.py
toolchains/vivado.py

This PR also fixes resources gathering for nexus. Fixes issue https://github.com/SymbiFlow/fpga-tool-perf/issues/367 and https://github.com/SymbiFlow/fpga-tool-perf/issues/368.
There is only an issue which I am not sure how to fix around the LUT4 and Carry chains usage, as in the nextpnr log, both of the resources are expressed combined in the `OXIDE_COMB` element, so the final implementation resources might be misleading.

results: add DSP usage information

---

fpgaperf.py
infrastructure/tasks.py
project/up5k-nes.yaml
toolchains/nextpnr.py

This PR does the following:
- allows the `yosys+nextpnr-ice40` up5k-nes test to fail (seems that some extra RAM blocks are inferred in yosys, making the netlist unpleaceable due to lack of resources)
- updates RapidWright which seemed to cause `nextpnr-interchange` failures

Fix CI build

---

results/html/index.html

Before:
After:
Precise timestamp can still be checked by hovering over a particular datapoint.

Properly interpret dates

---

.github/workflows/gh-pages.yml

Pinned setup-gcloud action to version "v0", fixes the GCS URL link

Fix CI that generates the result page

---

.github/workflows/Tests.yml

Tests suite used to fail with out of disc space error: https://github.com/chipsalliance/fpga-tool-perf/actions/runs/2458256884. It is no longer the case, but as we are always downloading latest version of arch-defs, we can encourage this problem again in the future.
This PR moves jobs from Tests suite to run on custom-runners.

Use custom-runners to run Tests suite

---

.github/workflows/Automerge.yml

This allows new CI runs to automatically cancel the previous runs corresponding to the same branch. CI is still expected to fail.

ci: limit concurrency

---

conf/requirements.txt
infrastructure/runner.py

tdqm hides the logs/content with a progress bar. When failures occur, which is rather common in this repository, tqdm makes debugging complicated. This PR removes the usage of tqdm.

infrastructure/runner: no tqdm

---

toolchains/nextpnr.py

This option is included in edalize after its update so it's not necessary here
Signed-off-by: Robert Szczepanski <rszczepanski@antmicro.com>

Remove redundant log option

---

.github/workflows/Suite.yml

Recent changes to the Suite workflow missed the `--verbose` option added in #490. This PR adds it to the recently added jobs.

ci/Suite: enforce verbosity

---

Makefile

This PR ensures that the fpga-tool-perf tests use the latest interchange data uploaded to GCP. 
See also https://github.com/chipsalliance/fpga-interchange-tests/pull/131

Use the latest interchange data downloaded from GCP

---

.github/workflows/Automerge.yml
.github/workflows/Pages.yml
.github/workflows/Suite.yml

This commit moves jobs using gcp-storage-sync action to the custom runners and replaces the `gcp-storage-sync` action with direct `gsutil` calls.

Replace gcp-storage-sync action with gsutil

---

conf/requirements.txt

Pin the python-sat version to 0.1.7.dev19 to resolve problems with preparing a working environment in the CI.

Fix prepare enviromnent step in the CI

---

.github/scripts/get_rapidwright_link.sh
.github/workflows/Suite.yml

This PR adds a dedicated script for obtaining the RapidWright JAR link. The script has the following advantages over the previous approach:
- retries curl requests on failure
- checks whether the obtained link is valid 
- exits with the error code and additional debug info on failure

ci: Use verbose script for getting RapidWright JAR link

---

.github/workflows/Suite.yml

Adding bash as a default shell enforces `set -eo pipefail`, which prevents skipping errors in pipes.
More info is available in the [documentation of GitHub Actions](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)
Link to a CI [job](https://github.com/chipsalliance/fpga-tool-perf/actions/runs/3830944664/jobs/6519511200#step:4:55) showing that the solution works.

ci: Prevent skipping errors in pipes

---

.github/scripts/install.sh

After adding tbb library as a run dependency to conda, manual installation of the package in CI is no longer required.
Related to https://github.com/chipsalliance/fpga-tool-perf/pull/536#issuecomment-1369965277

Remove manual installation of tbb library after updating nextpnr-fpga-interchange conda package

---

.github/workflows/Suite.yml

This is a temporary workaround for a regression in gsutil which causes multithreaded uploads to fail if the `storage.buckets.get` permission is missing on the caller IAM.
The regression is further documented in the release notes: https://cloud.google.com/storage/docs/release-notes#January_19_2023
This commit should be reverted once the regression has been fixed.
Internal-tag: [#41010]
Signed-off-by: Adam Olech <aolech@antmicro.com>

ci: pin gcloud to 413.0.0-0

---

.github/workflows/Pages.yml
.github/workflows/Suite.yml
.github/workflows/Tests.yml

The CI is failing to spawn the machines. The issue seems to be the one described in https://github.com/chipsalliance/verible/issues/1663. Locking the image to ubuntu:focal-20221130 should fix the issue

CI: tie docker image to ubuntu:focal-20221130

---

.github/scripts/build_nextpnr_fpga_interchange.sh
toolchains/nextpnr.py

This PR contains fixes for building the nextpnr-fpga_interchange experimental single-thread toolchain. Without them, the toolchain is built exactly in the same way as the experimental version (with multithreading enabled)

Fix nextpnr-fpga_interchange-experimental-single-thread toolchain

---

toolchains/icestorm.py
toolchains/nextpnr.py
utils/utils.py

Recently we noticed that part of the instability in nextpnr-fpga_interchange toolchains was caused by incorrect usage of `str.lstrip()` and `str.rstrip()` functions during log parsing.
This PR changes the wrong occurrences of those function calls to `removeprefix()` and `removesuffix()` functions respectively. The functions from the python library (`str.removeprefix()`, `str.removesuffix()`) are not used because they were introduced in Python 3.9 and we want to be compatible with older versions of python.
The incorrect usage of `str.lstrip()` and `str.rstrip()` led to incorrect calculations of execution times in the `nextpnr-fpga_interchange` toolchain (most notably in the routing time results).

Fix usage of lstrip and rstrip

---

.github/workflows/Pages.yml
.github/workflows/Suite.yml
.github/workflows/Tests.yml

Pin the type of spawned GCP machines to make sure that we use the same type of devices to measure the performance.

Pin type of spawned GCP machines
